
# Backup & Restore Automation Workflow
name: Backup & Restore

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' 
jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Backup database
        run: python scripts/db_backup.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_PATH: backups/
