
# Database Migration Workflow
name: DB Migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python scripts/db_migrate.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
