
# Docker Build & Push Workflow
name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-data-pipeline:22.04 .

      - name: Push Docker image
        run: |
          docker tag my-data-pipeline:22.04 ${{ secrets.DOCKERHUB_USER }}/my-data-pipeline:22.04
          docker push ${{ secrets.DOCKERHUB_USER }}/my-data-pipeline:22.04
