
# GCP Deployment Workflow
name: GCP DataOps Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-data-pipeline:22.04 .

      - name: Push Docker image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-data-pipeline:22.04

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-data-pipeline \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-data-pipeline:22.04 \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
