# name: CronJob Workflow

# on: 

#     push:
#       branches: [main, develop, release/**]
#       paths:
#         - 'src/**'
#         - 'tests/**'

#     pull_request:
#       branches: [main, develop, release/**]
#       paths:
#         - 'src/**'
#         - 'tests/**'

#     schedule:
#       - cron: '2 * * * *' 

# jobs:

#   say-hello-world:

#     runs-on: ubuntu-latest

#     steps:

#       - name: Hello World
#         run: echo "Hello, World!"

on:
  repository_dispatch:
    types: [incident_report]

jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print incident details
        run: echo "Incident reported"
