name: jobs Workflow

on: 

    push:
      branches: [main, develop, release/**]
      # paths:
      #   - 'src/**'
      #   - 'tests/**'

    # pull_request:
    #   branches: [main, develop, release/**]
    #   paths:
    #     - 'src/**'
    #     - 'tests/**'

    # schedule:
    #   - cron: '2 * * * *' 

jobs:

  job_1:
    runs-on: ubuntu-22.04

    steps:
      - name: Hello World
        run: echo "Hello, World! from job_1"
  job_2:
    runs-on: ubuntu-22.04


    needs: job_1
    steps:
      - name: Hello World
        run: echo "Hello, World! from job_2"
  job_3:
    runs-on: ubuntu-22.04

    needs: [job_1, job_2]
    steps:
      - name: Hello World
        run: echo "Hello, World! from job_3"

